spring:
  application:
    name: newsletter

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/newsletter_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  docker:
    compose:
      enabled: true

  modulith:
    events:
      republish-outstanding-events-on-restart: true
      completion-mode: archive